CREATE TABLE EQUIPO (
    ID_EQUIPO INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION VARCHAR(255),
    UBICACION VARCHAR(255),
    MARCA VARCHAR(255) NOT NULL,
    MODELO VARCHAR(255) NOT NULL,
    ANO_FABRICACION INT,
    HORAS_MAQUINA INT NOT NULL
) ;
