CREATE TABLE TAREAS_EQUIPO (
    ID_TAREA INT AUTO_INCREMENT PRIMARY KEY,
    ID_EQUIPO INT NOT NULL,
    TAREA VARCHAR(255) NOT NULL,
    INTERVALO_HORAS_MAQUINA INT,
    FECHA_ULT_MANT DATE,
    CANT_HORAS INT,
    HORAS_SIG_MANTENIMIENTO INT,
    FECHA_SIG_MANTENIMIENTO DATE,
    ULTIMO_TECNICO VARCHAR(255),
    SIG_TECNICO_ASIGN VARCHAR(255),
    FOREIGN KEY (ID_EQUIPO)
        REFERENCES EQUIPO(ID_EQUIPO)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ;
