CREATE TABLE USUARIOS (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(150) NOT NULL,
    USUARIO VARCHAR(100) NOT NULL UNIQUE,
    CORREO VARCHAR(200) NOT NULL UNIQUE,
    CLAVE_HASH VARCHAR(255) NOT NULL,
    ROL VARCHAR(255) NOT NULL,
    ESTADO VARCHAR(255) NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ;
