
CREATE OR REPLACE VIEW V_TAREAS_MANTENIMIENTO AS
SELECT
    TE.ID_TAREA,
    TE.ID_EQUIPO,
    TE.TAREA,
    TE.INTERVALO_HORAS_MAQUINA,
    TE.CANT_HORAS,
    -- Cálculo de las horas restantes
    (TE.HORAS_SIG_MANTENIMIENTO - TE.CANT_HORAS) AS HORAS_RESTANTES_MANTENIMIENTO
FROM
    TAREAS_EQUIPO AS TE
    ORDER BY HORAS_RESTANTES_MANTENIMIENTO;